// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Shop struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Slug      string
	Status    string
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type ShopAddress struct {
	ID          pgtype.UUID
	ShopID      pgtype.UUID
	CountryID   int32
	CityID      int32
	DistrictID  int32
	WardID      int32
	AddressLine string
	ContactName string
	PhoneNumber string
	Type        string
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShopMember struct {
	ShopID   pgtype.UUID
	MemberID pgtype.UUID
	JoinedAt pgtype.Timestamptz
	AddedBy  pgtype.UUID
}

type ShopMemberRole struct {
	ShopID    pgtype.UUID
	MemberID  pgtype.UUID
	RoleID    int32
	UpdatedBy pgtype.UUID
}

type ShopProfile struct {
	ShopID      pgtype.UUID
	Description pgtype.Text
	LogoUrl     pgtype.Text
	BannerUrl   pgtype.Text
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShopRole struct {
	ID   int32
	Code string
	Name string
}
